# Copyright 2023 Salesforce, Inc. All rights reserved.
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: ingress-http
spec:
  address: http://0.0.0.0:8083
  services:
    upstream:
      address: http://host.docker.internal:8089
      routes:
        - config:
            destinationPath: /
      #  policies:
      #    - policyRef:
      #        name: group-payload-logging-policy-v1-0-impl # This value will be overriden during 'make run' execution
      #        namespace: default
      # Fill the config with a policy configuration that matches the schema specified in the policy
      # definition gcl.yaml. Eg:
      # config:
      #   someProperty: desiredValue
      # config: {}
  policies:
    - policyRef:
        name: group-payload-logging-policy-v1-1-impl
        namespace: default
